# Generated by Django 5.2.6 on 2025-10-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthday',
            new_name='birthday_user',
        ),
    ]
