# Generated by Django 5.2.6 on 2025-10-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_tag_birthday_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Тэги'},
        ),
    ]
